// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: document_image.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentImageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId string `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Pages      uint32 `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Filename   string `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	CreatedAt  uint64 `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  uint64 `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *DocumentImageReply) Reset() {
	*x = DocumentImageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_document_image_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentImageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentImageReply) ProtoMessage() {}

func (x *DocumentImageReply) ProtoReflect() protoreflect.Message {
	mi := &file_document_image_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentImageReply.ProtoReflect.Descriptor instead.
func (*DocumentImageReply) Descriptor() ([]byte, []int) {
	return file_document_image_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentImageReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DocumentImageReply) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentImageReply) GetPages() uint32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *DocumentImageReply) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DocumentImageReply) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DocumentImageReply) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListDocumentImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*DocumentImageReply `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListDocumentImage) Reset() {
	*x = ListDocumentImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_document_image_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDocumentImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentImage) ProtoMessage() {}

func (x *ListDocumentImage) ProtoReflect() protoreflect.Message {
	mi := &file_document_image_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentImage.ProtoReflect.Descriptor instead.
func (*ListDocumentImage) Descriptor() ([]byte, []int) {
	return file_document_image_proto_rawDescGZIP(), []int{1}
}

func (x *ListDocumentImage) GetList() []*DocumentImageReply {
	if x != nil {
		return x.List
	}
	return nil
}

type DocumentImageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocumentId string `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Disk       string `protobuf:"bytes,2,opt,name=disk,proto3" json:"disk,omitempty"`
	Pages      uint32 `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Extension  string `protobuf:"bytes,4,opt,name=extension,proto3" json:"extension,omitempty"`
}

func (x *DocumentImageInfo) Reset() {
	*x = DocumentImageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_document_image_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentImageInfo) ProtoMessage() {}

func (x *DocumentImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_document_image_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentImageInfo.ProtoReflect.Descriptor instead.
func (*DocumentImageInfo) Descriptor() ([]byte, []int) {
	return file_document_image_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentImageInfo) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentImageInfo) GetDisk() string {
	if x != nil {
		return x.Disk
	}
	return ""
}

func (x *DocumentImageInfo) GetPages() uint32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *DocumentImageInfo) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

type DocumentImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*DocumentImageRequest_Info
	//	*DocumentImageRequest_Content
	Data isDocumentImageRequest_Data `protobuf_oneof:"data"`
}

func (x *DocumentImageRequest) Reset() {
	*x = DocumentImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_document_image_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentImageRequest) ProtoMessage() {}

func (x *DocumentImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_image_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentImageRequest.ProtoReflect.Descriptor instead.
func (*DocumentImageRequest) Descriptor() ([]byte, []int) {
	return file_document_image_proto_rawDescGZIP(), []int{3}
}

func (m *DocumentImageRequest) GetData() isDocumentImageRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *DocumentImageRequest) GetInfo() *DocumentImageInfo {
	if x, ok := x.GetData().(*DocumentImageRequest_Info); ok {
		return x.Info
	}
	return nil
}

func (x *DocumentImageRequest) GetContent() []byte {
	if x, ok := x.GetData().(*DocumentImageRequest_Content); ok {
		return x.Content
	}
	return nil
}

type isDocumentImageRequest_Data interface {
	isDocumentImageRequest_Data()
}

type DocumentImageRequest_Info struct {
	Info *DocumentImageInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type DocumentImageRequest_Content struct {
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3,oneof"`
}

func (*DocumentImageRequest_Info) isDocumentImageRequest_Data() {}

func (*DocumentImageRequest_Content) isDocumentImageRequest_Data() {}

var File_document_image_proto protoreflect.FileDescriptor

var file_document_image_proto_rawDesc = []byte{
	0x0a, 0x14, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x22, 0xb5,
	0x01, 0x0a, 0x12, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x43, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x65, 0x72, 0x6d,
	0x65, 0x73, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x7c, 0x0a, 0x11, 0x44,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x69, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x69, 0x73, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x65,
	0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x6b, 0x0a, 0x14, 0x44, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2f, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x06,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x4c, 0x0a, 0x1a, 0x62, 0x72, 0x2e, 0x64, 0x65, 0x76,
	0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x50, 0x01, 0x5a, 0x09, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x2f, 0x70,
	0x62, 0xa2, 0x02, 0x03, 0x48, 0x4c, 0x57, 0xaa, 0x02, 0x1a, 0x62, 0x72, 0x2e, 0x64, 0x65, 0x76,
	0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x75, 0x73, 0x2e, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_document_image_proto_rawDescOnce sync.Once
	file_document_image_proto_rawDescData = file_document_image_proto_rawDesc
)

func file_document_image_proto_rawDescGZIP() []byte {
	file_document_image_proto_rawDescOnce.Do(func() {
		file_document_image_proto_rawDescData = protoimpl.X.CompressGZIP(file_document_image_proto_rawDescData)
	})
	return file_document_image_proto_rawDescData
}

var file_document_image_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_document_image_proto_goTypes = []interface{}{
	(*DocumentImageReply)(nil),   // 0: hermes.DocumentImageReply
	(*ListDocumentImage)(nil),    // 1: hermes.ListDocumentImage
	(*DocumentImageInfo)(nil),    // 2: hermes.DocumentImageInfo
	(*DocumentImageRequest)(nil), // 3: hermes.DocumentImageRequest
}
var file_document_image_proto_depIdxs = []int32{
	0, // 0: hermes.ListDocumentImage.list:type_name -> hermes.DocumentImageReply
	2, // 1: hermes.DocumentImageRequest.info:type_name -> hermes.DocumentImageInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_document_image_proto_init() }
func file_document_image_proto_init() {
	if File_document_image_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_document_image_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocumentImageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_document_image_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDocumentImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_document_image_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocumentImageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_document_image_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocumentImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_document_image_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*DocumentImageRequest_Info)(nil),
		(*DocumentImageRequest_Content)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_document_image_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_document_image_proto_goTypes,
		DependencyIndexes: file_document_image_proto_depIdxs,
		MessageInfos:      file_document_image_proto_msgTypes,
	}.Build()
	File_document_image_proto = out.File
	file_document_image_proto_rawDesc = nil
	file_document_image_proto_goTypes = nil
	file_document_image_proto_depIdxs = nil
}
